// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzdfmqovtwlilmpmvahf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZGZtcW92dHdsaWxtcG12YWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNDAyNzQsImV4cCI6MjA4ODgxNjI3NH0.b5TBaIxxP6ZtU0EqA1JdPVY6pPF5qW3M0441SUbUvO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});